### ISSUE TITLE
Answers

### ISSUE THREAD

**Issue by rasmus** [JC008/EventFlowGuide#1]
Hi

I had a look at your questions.

# Are there versioning requirements/needs for Aggregates?
Versioning is handled automatically by the aggregate root as each event applied is given the next version counter. This is also used to detect optimistic concurrency exceptions, i.e., when two different threads make changes to the same aggregate version.

# How can business rules be managed external to the Aggregate + be injected?
If you have complex business rules that you need to access from within your aggregate, then implement `IAggregateFactory` and install it. The default uses `Activator.CreateInstance(...)` to create aggregates, but you could create one that uses a IoC container allowing you to pass services into the aggregate constructor.

# Can an aggregate select a set of business rules to be applied for different versions or phases?
At my work we use a combination of feature toggles and event upgraders to handle this.

# Can commands be recorded / logged for auditing purposes?
You could add a [decorator](https://github.com/rasmus/EventFlow/blob/develop/Documentation/Customize.md] that does this. I'm currently working on adding IDs to commands which will help a bit with this.

# How is lookup data managed (e.g. City, Province, State etc etc)?
At work we pass services from the command handler to the aggregate on the aggregate methods. Your command handlers is created by the IoC container and can therefore depend on other services.

# How does an aggregate load an aggregate?
Not sure why you ever want to do this. Create a read model based on the other aggregate, then create a domain services that wraps that read model nicely and then pass that domain service to the aggregate.

# How can more/new readmodels be projected later in an application life cycle?
Good question and very relevant. In an event source system you can either loop through all events in the event source to rebuild all read models or you can do it for the read models of a single aggregate. I have worked a bit on it and its somewhat stable (see `IReadModelPopulator`), but the implementation doesn't "feel right" yet.

# Are read models ever used by entities / models / aggregates?
Yes, but wrapped behind a domain service or [queries](https://github.com/rasmus/EventFlow/blob/develop/Documentation/Queries.md).

# Is there a need to create explicit/classic "Models" or is AggregateRoot and ReadModels all that is needed?
Well, you could just have a system with only aggregate roots and not event read models, but that would make the system slow and aggregate root tend to be slow to load (until I get around to implement snapshotting).

# How can all Commands/Handers/Events etc etc be listed at runtime?
Nothing yet, and not sure I'll provide it in EventFlow. But its fairly easy, just loop through the assembly types or access them through the IoC container (although the latter will create the objects).

# How can a distributed system be implemented in EventFlow?
I'm working on publishing to RabbitMQ maiking it a bit easier. At my work we use EventFlow in a micro service arch.

# Must all events be stored in a single event store?
Well, you could have multiple instances of EventFlow running as there's (by design) no static or ambient context in EventFlow, allowing multiple instances running in the same process.

# Can a sharding strategy be used for an EventStore to avoid overloading a single database server?
I guess if the support for [EventStore](https://geteventstore.com/) got production ready you could use that. But I think MSSQL does a fairly good job. We use it at work and migrate "old" aggregates to a separate archive event store when they aren't used any more.

# ISSUE Why does EventFlowOptionsDefaultExtensions.UseDefaults not load events?
Will be fixed in 0.11. I came across it myself when developing RabbitMQ support.

# Can events be broad-casted / queued?
Use RabbitMQ if its for external services.

# Can command handlers be implemented to be used remotely with NetMQ / JSONRPC / Remoting?
Commands are basically value objects, so if should be very easy to deserialize a command and send it to the command bus. So yes.

# Can a ReadModel be created that supports all/any storage mechanisms (not specifics like SQLServer) to enable moving between storage systems?
Currently there's only support for MSSQL and I'm working on Elasticsearch support, but you aren't limited to using a single read store. You could use MSSQL for some read models and then Elasticsearch for others, even implement your own as with the current version EventFlow it doesn't require much to implement a read store.

# How can EasyNetQ (RabiitMQ) be used with EventFlow?
I'm currently doing the publishing of events and will have a look at consuming commands soon.

# How can a system be configured at runtime to include or exclude commands, events etc (see Autofac modules concept)?
Create a decorator for those services and then use a feature toggle.

# How can EventFlow be used in a micro services configuration/setup/scenario?
Well, it depends :)

**Comment by JC008** [comment]
@rasmus Thanks for the valuable feedback and keep up the excellent work on EventFlow.
